// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaPXDBcP9yBymj_X3DsY646qd6STEHWac',
    appId: '1:304115013250:web:49526512fae3fbcccec69b',
    messagingSenderId: '304115013250',
    projectId: 'fitnessapp-54498',
    authDomain: 'fitnessapp-54498.firebaseapp.com',
    storageBucket: 'fitnessapp-54498.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS_0_WwaXfdMUlFGKVKOIm7sqpf539kQM',
    appId: '1:304115013250:android:fe51d3e739383b71cec69b',
    messagingSenderId: '304115013250',
    projectId: 'fitnessapp-54498',
    storageBucket: 'fitnessapp-54498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEEftWaphi5ugYAgPZQJLy40bypcjmeMQ',
    appId: '1:304115013250:ios:fb831cc003b871f5cec69b',
    messagingSenderId: '304115013250',
    projectId: 'fitnessapp-54498',
    storageBucket: 'fitnessapp-54498.appspot.com',
    iosClientId: '304115013250-3pqd833hhpv249hjrad0tufcvj1sk2nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEEftWaphi5ugYAgPZQJLy40bypcjmeMQ',
    appId: '1:304115013250:ios:5bed77cbf7dd5fbfcec69b',
    messagingSenderId: '304115013250',
    projectId: 'fitnessapp-54498',
    storageBucket: 'fitnessapp-54498.appspot.com',
    iosClientId: '304115013250-qj0sst5ja5fh78ajb4mh8fk2ipagaav9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp.RunnerTests',
  );
}
